plugins {
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.1.1'
}

group = 'io.github.Akfz'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

tasks.withType(Javadoc).configureEach {
    options.addStringOption('Xdoclint:none', '-quiet')
    options.encoding = 'UTF-8'
}

gradlePlugin {
    website = 'https://github.com/Akfz/DbuildG'
    vcsUrl  = 'https://github.com/Akfz/DbuildG'

    plugins {
        DbuildGradle {
            id                  = 'io.github.Akfz.dbg'
            implementationClass = 'v.akfz.dbg.DbuildGradlePlugin'
            displayName         = 'Dbuild multiloader plugin'
            description         = 'Single-project multiloader plugin for Fabric/Forge/NeoForge'
            tags.set(['minecraft', 'multiloader', 'mods'])
        }
    }
}